# EduBox Docker Compose Configuration
# This is the main docker-compose file for easy deployment

version: '3.8'

services:
  edubox:
    build:
      context: .
      dockerfile: Dockerfile.simple  # Using simplified version by default
    container_name: edubox
    ports:
      - "80:80"     # Main web interface
      - "8080:8080" # Kiwix/Wikipedia
    volumes:
      - ./content:/opt/edubox/content
      - ./logs:/opt/edubox/logs
      - ./backup:/opt/edubox/backup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Volumes for persistent data
volumes:
  content:
    driver: local
  logs:
    driver: local
  backup:
    driver: local