version: '3.8'

services:
  edubox:
    image: edubox:latest
    container_name: edubox
    ports:
      - "80:80"      # Main web interface
      - "8080:8080"  # Kolibri/Khan Academy (when using full version)
      - "8081:8081"  # Kiwix/Wikipedia
    volumes:
      - ./content:/opt/edubox/content
      - ./logs:/opt/edubox/logs
      - ./backup:/opt/edubox/backup
    environment:
      - KOLIBRI_ADMIN_USER=admin
      - KOLIBRI_ADMIN_PASS=changeme
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - edubox-net

networks:
  edubox-net:
    driver: bridge

volumes:
  content:
  logs:
  backup: